import { useEffect, useRef, useState } from "react";
import { inputClasses, labelClasses, buttonPrimaryClasses, buttonSecondaryClasses, errorTextClasses, modalOverlayClasses, modalPanelClasses } from "../lib/ui";

export default function Modal({ title, fields, initialValues = {}, onSubmit, onClose, submitLabel = "Save" }) {
  const [values, setValues] = useState(initialValues); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const panelRef = useRef(null); const firstFieldRef = useRef(null);
  useEffect(() => { firstFieldRef.current?.focus(); function handleKeyDown(e) { if (e.key === "Escape") onClose(); if (e.key === "Tab" && panelRef.current) { const focusable = panelRef.current.querySelectorAll("input, select, textarea, button:not([disabled])"); if (!focusable.length) return; const first = focusable[0], last = focusable[focusable.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } } } document.addEventListener("keydown", handleKeyDown); return () => document.removeEventListener("keydown", handleKeyDown); }, [onClose]);
  async function handleSubmit(e) { e.preventDefault(); setError(""); setSubmitting(true); try { await onSubmit(values); } catch (err) { setError(err.message || "Something went wrong"); } finally { setSubmitting(false); } }
  return <div className={modalOverlayClasses} onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div ref={panelRef} role="dialog" aria-modal="true" aria-labelledby="modal-title" className={modalPanelClasses}><div className="mb-6 flex items-start justify-between gap-4"><h2 id="modal-title" className="text-2xl font-semibold tracking-tight text-[#17202b]">{title}</h2><button type="button" onClick={onClose} aria-label="Close dialog" className="min-h-11 min-w-11 rounded-xl text-2xl text-[#7a8795] hover:bg-[#f5f7fa]">×</button></div><form onSubmit={handleSubmit} noValidate className="flex flex-col gap-4">{fields.map((field, i) => <div key={field.name}><label htmlFor={field.name} className={labelClasses}>{field.label}{field.required && " *"}</label>{field.type === "select" ? <select id={field.name} ref={i === 0 ? firstFieldRef : undefined} required={field.required} value={values[field.name] ?? ""} onChange={(e) => setValues((v) => ({ ...v, [field.name]: e.target.value }))} className={inputClasses}><option value="" disabled>Select…</option>{field.options?.map((opt) => <option key={opt.value} value={opt.value}>{opt.label}</option>)}</select> : field.type === "textarea" ? <textarea id={field.name} ref={i === 0 ? firstFieldRef : undefined} required={field.required} rows={3} value={values[field.name] ?? ""} onChange={(e) => setValues((v) => ({ ...v, [field.name]: e.target.value }))} className={inputClasses} /> : <input id={field.name} ref={i === 0 ? firstFieldRef : undefined} type={field.type ?? "text"} required={field.required} value={values[field.name] ?? ""} onChange={(e) => setValues((v) => ({ ...v, [field.name]: e.target.value }))} className={inputClasses} />}</div>)}{error && <p role="alert" className={errorTextClasses}>{error}</p>}<div className="flex flex-col-reverse gap-3 pt-3 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className={buttonSecondaryClasses}>Cancel</button><button type="submit" disabled={submitting} className={buttonPrimaryClasses}>{submitting ? "Saving…" : submitLabel}</button></div></form></div></div>;
}
